sudo: required

services:
- docker

before_install:
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in ./project/travis/travis.secring.asc.enc -out local.secring.asc -d
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in ./project/travis/travis.pubring.asc.enc -out local.pubring.asc -d

addons:
  firefox: "61.0.2"

language: scala

before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - docker info
  - docker pull danjellz/http-server
  - docker run --name web -d -p 8080:8080 -v $PWD/pawl-scalatest/src/it/resources:/public danjellz/http-server
  - curl -s https://aerokube.com/cm/bash | bash
  - ./cm selenoid start --vnc --args "-limit 2"
  - docker logs selenoid
  - curl http://localhost:4444/wd/hub
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16"
  - ./project/travis/install-geckodriver.sh

matrix:
  include:
  - scala: 2.12.4
    jdk: oraclejdk8
    script:
      - sbt ';compile;test;package;it:test'
    after_success: ./project/travis/travis-ci-sonatype-deploy.sh
    after_failure: ./project/travis/tarvis-ci-yandex-logs-upload.sh

notifications:
  slack:
    secure: Y2G6IeDaDnTaJY7d5xObje7IbNV70aPztrljmMboPNiWI8eyjzrEMLYhqAJgY3cEKBlZSHMyy6TB7vHEEL9ugSOEPCOyKaGjEMhSRn6RT/9XnBa2lfkctuv5cZBZvkW7CZ+Fea61SP80ZUmlZWpfNO9lvYg4/w2lqoN92Mi0qCPc/ZlBRMWFMc0Jkc0Ph6ByEp8MhwdOON3SCUHjxHkbOKl1B141rlhuusDKh7rmBwRuCj0fH/iZ2W4fijMdWolc7D0JN43UqUoHJYsopGr8pCmlU++5skukV/RUfLwE3YOsCrV07mtiGlINRERdJAOrC2UtMkptqHn710MDnEAPwC9OFFfzh7Xe02w+iGNW7FTPwHhrDv1nxX1+z0uBK8QiuKJFkHa26hbMh7PpVv4MQJZUtF1z6d20KVU9L7MkSVgbniuD6MOy1N6BvJZCZWndaUjleUp1zbTJbqSVhLXWRPZVQfGworsCy8EoqGWjx6/h+kd23THjE5WruT78peHhmyJniaAYdJVPZuCOgNWNmsK6zsOFsd3trt7d9/4UtwmqybC4GrRNG9ZHFLWE6seaiC3bSdt+8wumZuVNGlcwqkFAq60OpRGflAy8lOzlKAXHCz+zO85mV6x7UfNvC3Sc5zwmxoQb18RABFZvLWTrpEJyWh6fcKgPSK6czo7CKz4=

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  bundler: true
  directories:
  - $HOME/.m2/repository
  - $HOME/.sbt/boot
  - $HOME/.ivy2/cache
  - $HOME/docker
before_cache:
# Save tagged docker images
- >
  mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
  | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

env:
  global:
    secure: Q3Cu/FlIOJmW0P7G+2zVWJHbs1gl/rS5IXP6h34nFiAN63DG7XZrjvY3Jgdl5ZfAJyM+SczaLVYyQ6wmIe4zqjZA9BaEIjRAAHeyIj9nV76oKGh6Asai4DfoughOiUpe8WSfvdFd7IJ358sX4/TPjhgDRG0qckWucSS9wggnF9LcwulLjTxuF0zFHN04FL1Jtmk/GltSHz1GJ+abBGTqVMK77SyPlM+MqCfot3EAQD/2zHMZvOLJ6VZkF7zknsuQCCvEhckbm02XaSl6EIFuWdu5xnSDY6FXiANmHgLt+oYbKkrLHiAJI7/AwsRzs+jZTE+VPZjw9gFcbtuLKdwTzmLAC7quPRDIVaHaNhojo8KwC6pMoMm0W4IDSVi7XARYB0zvbqFajQaYF77Je5j61slKj1+CZtO6+jvUoT5zEwyGDzc+1u7IL7rWq44EgD0KUVzeXjT/92P00Mu3ZpfnnEXFKAQyCl7UmKY1mv+NcLR4+fxEh7bv1R97+PB0VblRrtG6tIjm9AG3rPKp8s5wUg6e6q5PPGFZE1KC52cIeqVpdViTeMIIEY6zIDB1yRPncduHeaXVA9NfKu4WcKwK9RQd+pQaOSbPc/Qfg/mY8TbeKUITXE9ATP8rnNomi2yhdamttxB4wCg+KRRpy1NjjAyPiyCgoRmg4W0PG/kolk0=
